#!/bin/bash --norc
set -euo pipefail

script_dir="$(dirname "${BASH_SOURCE[0]}")"

if which launchctl 1>/dev/null 2>/dev/null; then
  exec "$script_dir/install-launchd" "$@"
fi

echo Failed to determine correct installer for this system >&2
exit 1
