#!/usr/bin/env python3

import logging
import os

from nightlife.installer import install_launchd


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG if os.getenv("DEBUG") else logging.INFO)

    install_launchd()
