#!/usr/bin/env python3

"""
Run the nightlife agent server application.

Server address information is written to the agent lockfile before invoking the
server.

This executable invokes uvicorn to run the webserver as a subprocess.
"""

import argparse
import os
import subprocess
import sys

from nightlife.config import AGENT_LOCKFILE, write_lockfile


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8001)
    args, extra_args = parser.parse_known_args()

    write_lockfile(AGENT_LOCKFILE, args.host, args.port)

    try:
        p = subprocess.run(
            [
                "uvicorn",
                "nightlife.agent:app",
                f"--host={args.host}",
                f"--port={args.port}",
            ] + extra_args,
            stdin=sys.stdin,
        )
        returncode = p.returncode
    except KeyboardInterrupt:
        returncode = 0
    finally:
        os.unlink(AGENT_LOCKFILE)

    sys.exit(returncode)


if __name__ == "__main__":
    main()
