#!/usr/bin/env python3

import logging
import os
import sys

from nightlife.system import which


def main() -> None:
    logging.basicConfig(
        level=logging.DEBUG if os.getenv("DEBUG") else logging.INFO,
        format="%(asctime)s|%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    if which("launchctl") is not None:
        from nightlife.installer import install_launchd
        install_launchd()
    else:
        logging.error("Failed to determine correct installer for this system")
        sys.exit(1)


if __name__ == "__main__":
    main()
