#!/usr/bin/env python3

"""
Notify a running principal server that an event should be dispatched.

This tool makes an HTTP POST request against the /dispatch/$event endpoint of
the target principal server for the given event name. The body of the HTTP
response is written to stdout.

By default, the principal server address is read from the principal server
lockfile on the local machine. However, if the principal you want to notify is
on a different machine, you can specify a custom server address.
"""

import argparse
import logging
import os
import sys
import urllib.request

from nightlife.config import PRINCIPAL_LOCKFILE


def main() -> None:
    logging.basicConfig(
        level=logging.DEBUG if os.getenv("DEBUG") else logging.INFO,
        format="%(asctime)s|%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    parser = argparse.ArgumentParser()
    parser.add_argument("event")
    parser.add_argument("--principal-host")
    parser.add_argument("--principal-lockfile", default=PRINCIPAL_LOCKFILE)
    args = parser.parse_args()

    if args.principal_host is None:
        with open(args.principal_lockfile, "r") as f:
            args.principal_host = f.read()

    url = f"{args.principal_host}/dispatch/{args.event}"
    logging.info("POST %s", url)

    request = urllib.request.Request(url, method="POST")
    with urllib.request.urlopen(request) as f:
        sys.stdout.buffer.write(f.read())


if __name__ == "__main__":
    main()
