#!/usr/bin/env python3

import os
import sys

from nightlife.topic_handler_utils import topic_state_file

THEMEFILE = topic_state_file("theme", "themefile")


if __name__ == "__main__":
    os.makedirs(os.path.dirname(THEMEFILE), exist_ok=True)
    with open(THEMEFILE, "w") as f:
        f.write(sys.stdin.read())
